name: Elixir CI

on:
  push:
    branches: [ master ]
  pull_request:

jobs:
  build:

    name: Build and test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - elixir: 1.6.6
            otp: 19.3
          - elixir: 1.7.4
            otp: 19.3
          - elixir: 1.8.2
            otp: 20.3
          - elixir: 1.9.4
            otp: 20.3
          - elixir: 1.10.3
            otp: 22.3
          - elixir: 1.11.2
            otp: 21.3
          - elixir: 1.11.2
            otp: 23.0
    steps:
    - uses: actions/checkout@v2
    - name: Set up Elixir
      uses: actions/setup-elixir@v1
      with:
        elixir-version: ${{ matrix.elixir }} # Define the elixir version [required]
        otp-version: ${{ matrix.otp }} # Define the OTP version [required]
    - name: Restore dependencies cache
      uses: actions/cache@v2
      with:
        path: deps
        key: ${{ runner.os }}-${{ matrix.otp }}-${{ matrix.elixir }}-mix-${{ hashFiles('**/mix.lock') }}
        restore-keys: ${{ runner.os }}-${{ matrix.otp }}-${{ matrix.elixir }}-mix-
    - name: Install dependencies
      run: mix deps.get
    - name: Run tests
      run: mix test
