name: Elixir CI

on:
  push:
    branches: [ master ]
  pull_request:

jobs:
  build:

    name: Build and test
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        include:
          - elixir: "1.10"
            otp: 22.3
          - elixir: "1.11"
            otp: 23.3
          - elixir: "1.12"
            otp: 23.3
          - elixir: "1.13"
            otp: 23.3
          - elixir: "1.13"
            otp: 24.3
          - elixir: "1.14"
            otp: 24.3
          - elixir: "1.14"
            otp: 25.1
    steps:
    - uses: actions/checkout@v2
    - name: Set up Elixir
      uses: erlef/setup-beam@v1
      with:
        elixir-version: ${{ matrix.elixir }} # Define the elixir version [required]
        otp-version: ${{ matrix.otp }} # Define the OTP version [required]
    - name: Restore dependencies cache
      uses: actions/cache@v2
      with:
        path: deps
        key: ${{ runner.os }}-${{ matrix.otp }}-${{ matrix.elixir }}-mix-${{ hashFiles('**/mix.lock') }}
        restore-keys: ${{ runner.os }}-${{ matrix.otp }}-${{ matrix.elixir }}-mix-
    - name: Install dependencies
      run: mix deps.get
    - name: Run tests
      run: mix test

  format:
    name: Format
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        include:
          - elixir: 1.14
            otp: 25.1
    steps:
    - uses: actions/checkout@v2
    - name: Set up Elixir
      uses: erlef/setup-beam@v1
      with:
        elixir-version: ${{ matrix.elixir }} # Define the elixir version [required]
        otp-version: ${{ matrix.otp }} # Define the OTP version [required]
    - name: Restore dependencies cache
      uses: actions/cache@v2
      with:
        path: deps
        key: ${{ runner.os }}-${{ matrix.otp }}-${{ matrix.elixir }}-mix-${{ hashFiles('**/mix.lock') }}
        restore-keys: ${{ runner.os }}-${{ matrix.otp }}-${{ matrix.elixir }}-mix-
    - name: Install dependencies
      run: mix deps.get
    - name: Check format
      run: mix format --check-formatted
